services:
  saltplayer:
    image: ghcr.io/kkw114/saltplayer:latest
    ports:
      - "3000:3000"
    volumes:
      - ./music:/music
    environment:
      - MUSIC_DIR=/music
      - PORT=3000
    restart: unless-stopped
